function Comp = addComponents2Panel_View(hPanel)

FC = [255 255 102]/255;
pos = [0 0.5 0.5 0.5
           0.5 0.5 0.5 0.5
           0 0 0.5 0.5
           0.5 0 0.5 0.5];

TT = {'Axial'
           '3D'
           'Coronal'
           'Sagittal'};

for n = 1:4

    Comp.hPanel(n) = uipanel('parent', hPanel,...
                                    'Unit', 'Normalized',...
                                    'Position', pos(n, :), ...
                                    'Title', TT{n},...
                                    'FontSize',                 12,...
                                    'Units',                     'normalized', ...
                                    'visible',                      'on', ...
                                    'ForegroundColor',       FC,...
                                    'BackgroundColor',       'k', ...
                                    'HighlightColor',          'c',...
                                    'ShadowColor',            'k');
    
    % axes
    Comp.hAxis(n).Image = axes('Parent', Comp.hPanel(n), ...
                                'color',        'none',...
                                'xcolor', FC,...
                                'ycolor', FC, ...
                                'gridcolor',   FC,...
                                'Units',                    'normalized', ...
                                'HandleVisibility',     'callback', ...
                                'Position',                 [0.05 0.05 0.9 0.9]);
    
%     Comp.hAxis.Image(n).XAxisLocation = 'top';

%     hold(Comp.hAxis.Image(n), 'on')

end

Comp.hAxis(2).Image.Visible = 'off';