 function Comp = addComponents2Panel_LoadImage(hPanel)

y1 = 0.8;
 h_Button = 0.1;

BC_PB = [1 1 1]*0.25;

FS = 8;

% load image
Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load  Volume',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 y1 0.6 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_LoadImagePanel_LoadImage);
                            