 function Comp = addComponents2Panel_LoadImage(hPanel)

 h_Button = 0.1;
 h_Gap = 0.1;

BC_PB = [1 1 1]*0.25;

FS = 8;

y = 0.8;
% load image
Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load  Volume',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 y 0.6 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_LoadImagePanel_LoadImage);

y = y-h_Button-h_Gap;
% load image
Comp.Pushbutton.Seg = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Segmentation',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 y 0.6 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_LoadImagePanel_Seg);
